import { CoreMenu } from "@core/types";

export const menu: CoreMenu[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    translate: "MENU.DASHBOARD.COLLAPSIBLE",
    type: "collapsible",
    icon: "home",
    badge: {
      title: "2",
      translate: "MENU.DASHBOARD.BADGE",
      classes: "badge-light-warning badge-pill",
    },
    children: [
      {
        id: "analysisForm",
        title: "analysisForm",
        translate: "Analysis",
        type: "item",
        icon: "circle",
        url: "dashboard/analysisFrom",
      },
      {
        id: "analytics",
        title: "Analytics",
        translate: "MENU.DASHBOARD.ANALYTICS",
        type: "item",
        role: ["Admin"],
        icon: "circle",
        url: "apps/injury/statsInjury",
      },
      {
        id: "ecommerce",
        title: "User Analytics",
        translate: "MENU.DASHBOARD.ECOMMERCE",
        type: "item",
        icon: "circle",
        url: "dashboard/ecommerce",
      },
    ],
  },
  {
    id: "apps-and-pages",
    type: "section",
    title: "Apps & Pages",
    translate: "MENU.APPS.SECTION",
    icon: "package",
    children: [
      // {
      //   id: "email-app",
      //   title: "Profile",
      //   translate: "MENU.APPS.EMAIL",
      //   type: "item",
      //   icon: "mail",
      //   url: "apps/email",
      // },
      {
        id: "users",
        title: "Profile",
        translate: "MENU.APPS.USER.COLLAPSIBLE",
        type: "collapsible",
        icon: "user",
        role: ["Admin"],
        children: [
          {
            id: "list",
            title: "List",
            translate: "MENU.APPS.USER.LIST",
            type: "item",
            icon: "circle",
            url: "apps/user/user-list",
          },
        ],
      },
      {
        id: "training-sessions",
        title: "Training Sessions",
        type: "item",
        icon: "calendar",
        url: "teams/session",
      },

      {
        id: "matches",
        title: "Matches",
        type: "item",
        icon: "calendar",
        url: "teams/match",
      },
      {
        id: "meetings",
        title: "Meetings",
        // translate: 'MENU.APPS.CALENDAR',
        type: "item",
        icon: "calendar",
        url: "apps/meetings/playerslist",
      },
      {
        id: "Forum",
        title: "Forum",
        // translate: "MENU.APPS.TRAINING",
        type: "item",
        icon: "message-square",
        url: "/teams/forum",
      },
    ],
  },

  {
    id: "playersInjuries",
    title: "Players Injuries",
    //translate: 'MENU.APPS.PLAYERSINJURIES.COLLAPSIBLE',
    type: "collapsible",
    icon: "plus-circle",
    children: [
      {
        id: "injuriesList",
        title: "Injuries List",
        // translate: 'MENU.APPS.PLAYERSINJURIES.LIST',
        type: "item",
        icon: "circle",
        role: ["Admin"],
        url: "apps/injury/listInjury",
      },
      {
        id: "addInjury",
        title: "Add Injury",
        // translate: 'MENU.APPS.PLAYERSINJURIES.ADD',
        type: "item",
        icon: "circle",
        role: ["Admin"],
        url: "apps/injury/addInjury",
      },
      {
        id: "coachInjuryBack",
        title: " Injury Players ",
        // translate: 'MENU.APPS.PLAYERSINJURIES.ADD',
        type: "item",
        icon: "circle",
        role: ["Coach"],
        url: "apps/injury/coachInjuryBack",
      },
      {
        id: "physoInjuryBack",
        title: " Injury players",
        // translate: 'MENU.APPS.PLAYERSINJURIES.ADD',
        type: "item",
        icon: "circle",

        role: ["Physiotherapist"],

        url: "apps/injury/physoInjuryBack",
      },
      // {
      //   id: "statsInjury",
      //   title: "Stats Injury",
      //   // translate: 'MENU.APPS.PLAYERSINJURIES.ADD',
      //   type: "item",
      //   icon: "circle",
      //   url: "apps/injury/statsInjury",
      // },
      {
        id: "predictionInjury",
        title: "Prediction",
        // translate: 'MENU.APPS.PLAYERSINJURIES.ADD',
        type: "item",
        icon: "circle",
        url: "apps/injury/prediction",
      },
    ],
  },
];
